import assert from "node:assert/strict";
import { test } from "node:test";
import { readFileSync } from "node:fs";
import { backendAvailable, backendSource } from "@/lib/legacy/backendSource";

/**
 * The in-room live-caption rail and its CC button are gone — by decision.
 *
 * The owner asked for the panel in the room (the one headed "Transcript" with
 * हि/En · English · ଓଡ଼ିଆ tabs) and its control-bar button to be removed. What
 * these pin is the SCOPE of that removal, because the word "transcript" names
 * two different things here:
 *
 *   · the live rail — the browser's SpeechRecognition, writing the local
 *     participant's words into `meeting_transcripts`. Removed.
 *   · the after-meeting transcript in the details rail — generated by Gemini
 *     from the Drive audio, read from `/cowork/audio/transcript/:id`. Kept,
 *     and unaffected: nothing it reads was written by the live rail.
 *
 * Getting the scope wrong in either direction is the failure: leaving a CC
 * button that opens nothing, or taking the meeting's record away with it.
 */

function code(path: string): string {
  return readFileSync(path, "utf8")
    .replace(/\/\*[\s\S]*?\*\//g, "")
    .replace(/^\s*\/\/.*$/gm, "");
}

const ROOM = code("components/features/meetings/MeetingRoom.tsx");
const DETAIL = code("components/features/meetings/MeetingDetailArea.tsx");
const BAR = code("components/features/meetings/MeetingControlBar.tsx");

/* ── gone from the room ──────────────────────────────────────────────────── */

test("the live-caption rail is no longer mounted in the room", () => {
  assert.doesNotMatch(ROOM, /<TranscriptPanel/);
  assert.doesNotMatch(ROOM, /import \{ TranscriptPanel \}/);
});

test("nothing in the room drives a transcript toggle any more", () => {
  /* The state, the masthead button and the control-bar `captions` prop all
     went together: one of them left behind is a control that does nothing. */
  assert.doesNotMatch(ROOM, /transcriptOpen|setTranscriptOpen/);
  assert.doesNotMatch(ROOM, /captions=\{\{/);
  assert.doesNotMatch(ROOM, /"Show transcript"|"Hide transcript"/);
});

test("the control bar draws no CC button when no captions are passed", () => {
  /* The bar keeps its optional `captions` support rather than being edited —
     the button was always conditional on the prop, and every other room already
     passed none. Removing the prop from the last caller is the whole change. */
  assert.match(BAR, /captions\?: \{ on: boolean; toggle: \(\) => void \}/);
  assert.match(BAR, /showOnRow\.captions && captions &&/);
  for (const path of [
    "components/features/meetings/MeetingRoom.tsx",
    "components/features/meetings/TaskRoom.tsx",
    "components/features/meetings/GuestMeetingArea.tsx",
    "components/features/meetings/GuestRoom.tsx",
  ]) {
    assert.doesNotMatch(code(path), /captions=\{/, `${path} still passes captions`);
  }
});

/* ── kept in the rail ────────────────────────────────────────────────────── */

test("the after-meeting transcript in the details rail is untouched", () => {
  assert.match(DETAIL, /<VerbatimTranscriptPanel/);
  assert.match(DETAIL, /import \{ VerbatimTranscriptPanel \}/);
});

test(
  "that transcript is generated from the audio, not from the live rail",
  {
    skip: backendAvailable()
      ? false
      : "the engine checkout was not found — set COWORK_BACKEND",
  },
  () => {
    /* The proof the removal is safe: the surviving transcript reads a
       different collection through a different route, produced by Gemini
       from Drive. Resolved per-machine, and CRLF-normalised, by
       `backendSource` — this hardcoded `D:/GRAV_Project/...`, so it threw
       ENOENT on any other checkout. See `cowork-source-text-tests-hazard`. */
    const media = code("lib/legacy/meetingMedia.ts");
    assert.match(media, /\/cowork\/audio\/transcript\//);
    const summary = backendSource(
      "routes/task_routes/meetingSummary.routes.js",
    );
    assert.match(summary, /"meeting_transcripts_gemini"/);
    assert.doesNotMatch(summary, /"meeting_transcripts"\b/, "the summary reads the live rail");
  },
);

/* ── the help corpus, per CLAUDE.md ──────────────────────────────────────── */

test("the help source no longer lists CC among the room's controls", () => {
  const help = readFileSync("lib/help/knowledge.ts", "utf8");
  assert.doesNotMatch(help, /Raise hand, React, CC, Chat, People/);
  assert.match(help, /live-caption rail and its CC button were removed/);
});

test("no article ever described the live rail to a reader, so none went stale", () => {
  /* Checked rather than assumed: a stale answer is the failure CLAUDE.md names.
     The only "captions" in the corpus is a task-row sentence, unrelated. */
  const help = readFileSync("lib/help/knowledge.ts", "utf8");
  assert.doesNotMatch(help, /Show captions|Hide captions|as each participant speaks/);
});
