/**
 * Catalog entries for the extended library — how each of the newer functions
 * READS (signature, one line, an example). `catalog.ts` merges these into
 * `FUNCTION_HELP`; the catalog test still holds every registered function to
 * an entry, so this file and the function modules move together.
 */

import type { FnArg, FunctionHelp } from "../catalog";

const req = (name: string): FnArg => ({ name });
const opt = (name: string): FnArg => ({ name, optional: true });
const rep = (name: string): FnArg => ({ name, optional: true, repeatable: true });

const e = (
  name: string,
  category: FunctionHelp["category"],
  args: FnArg[],
  summary: string,
  example: string,
  signature?: string,
): FunctionHelp => (signature ? { name, category, args, summary, example, signature } : { name, category, args, summary, example });

const entries: FunctionHelp[] = [
  /* ── Math ──────────────────────────────────────────────────────────── */
  e("SQRT", "Math", [req("number")], "Returns the positive square root of a number.", "SQRT(16)"),
  e("EXP", "Math", [req("number")], "Returns e raised to the power of a number.", "EXP(1)"),
  e("LN", "Math", [req("number")], "Returns the natural logarithm of a number.", "LN(10)"),
  e("LOG", "Math", [req("number"), opt("base")], "Returns the logarithm of a number to a base, 10 when none is given.", "LOG(8, 2)"),
  e("LOG10", "Math", [req("number")], "Returns the base-10 logarithm of a number.", "LOG10(1000)"),
  e("PI", "Math", [], "Returns the value of pi to 15 digits.", "PI()"),
  e("SIGN", "Math", [req("number")], "Returns -1, 0 or 1 for the sign of a number.", "SIGN(-7)"),
  e("SIN", "Math", [req("angle")], "Returns the sine of an angle given in radians.", "SIN(PI()/2)"),
  e("COS", "Math", [req("angle")], "Returns the cosine of an angle given in radians.", "COS(0)"),
  e("TAN", "Math", [req("angle")], "Returns the tangent of an angle given in radians.", "TAN(RADIANS(45))"),
  e("ASIN", "Math", [req("value")], "Returns the inverse sine of a value, in radians.", "ASIN(1)"),
  e("ACOS", "Math", [req("value")], "Returns the inverse cosine of a value, in radians.", "ACOS(0)"),
  e("ATAN", "Math", [req("value")], "Returns the inverse tangent of a value, in radians.", "ATAN(1)"),
  e("ATAN2", "Math", [req("x"), req("y")], "Returns the angle from the x-axis to the point (x, y), in radians.", "ATAN2(1, 1)"),
  e("SINH", "Math", [req("value")], "Returns the hyperbolic sine of a value.", "SINH(1)"),
  e("COSH", "Math", [req("value")], "Returns the hyperbolic cosine of a value.", "COSH(1)"),
  e("TANH", "Math", [req("value")], "Returns the hyperbolic tangent of a value.", "TANH(1)"),
  e("DEGREES", "Math", [req("angle")], "Converts an angle in radians to degrees.", "DEGREES(PI())"),
  e("RADIANS", "Math", [req("angle")], "Converts an angle in degrees to radians.", "RADIANS(180)"),
  e("SQRTPI", "Math", [req("number")], "Returns the square root of a number multiplied by pi.", "SQRTPI(2)"),
  e("EVEN", "Math", [req("number")], "Rounds a number away from zero to the nearest even integer.", "EVEN(3)"),
  e("ODD", "Math", [req("number")], "Rounds a number away from zero to the nearest odd integer.", "ODD(4)"),
  e("PRODUCT", "Math", [req("value1"), rep("value2")], "Multiplies all the numbers given as arguments.", "PRODUCT(A1:A5)"),
  e("SUMSQ", "Math", [req("value1"), rep("value2")], "Returns the sum of the squares of the numbers.", "SUMSQ(3, 4)"),
  e("SUMPRODUCT", "Math", [req("array1"), rep("array2")], "Multiplies matching entries of the ranges and adds the products.", "SUMPRODUCT(A1:A5, B1:B5)"),
  e("QUOTIENT", "Math", [req("dividend"), req("divisor")], "Returns the whole-number part of a division.", "QUOTIENT(17, 5)"),
  e("GCD", "Math", [req("value1"), rep("value2")], "Returns the greatest common divisor of the integers.", "GCD(12, 18)"),
  e("LCM", "Math", [req("value1"), rep("value2")], "Returns the least common multiple of the integers.", "LCM(4, 6)"),
  e("MROUND", "Math", [req("number"), req("multiple")], "Rounds a number to the nearest multiple of another.", "MROUND(17, 5)"),
  e("FACT", "Math", [req("number")], "Returns the factorial of a number.", "FACT(5)"),
  e("FACTDOUBLE", "Math", [req("number")], "Returns the double factorial of a number.", "FACTDOUBLE(7)"),
  e("COMBIN", "Math", [req("n"), req("k")], "Returns the number of ways to choose k items from n.", "COMBIN(5, 2)"),
  e("PERMUT", "Math", [req("n"), req("k")], "Returns the number of ordered arrangements of k items from n.", "PERMUT(5, 2)"),
  e("CEILING.MATH", "Math", [req("number"), opt("significance"), opt("mode")], "Rounds a number up to the nearest multiple; mode rounds negatives away from zero.", "CEILING.MATH(-5.5, 1, 1)"),
  e("FLOOR.MATH", "Math", [req("number"), opt("significance"), opt("mode")], "Rounds a number down to the nearest multiple; mode rounds negatives toward zero.", "FLOOR.MATH(-5.5)"),
  e("ROMAN", "Math", [req("number")], "Converts a number to Roman numerals as text.", "ROMAN(1994)"),
  e("ARABIC", "Math", [req("roman_numeral")], "Converts a Roman numeral to a number.", "ARABIC(\"MCMXCIV\")"),
  e("SUBTOTAL", "Math", [req("function_code"), req("range1"), rep("range2")], "Returns a subtotal using the aggregate named by a code: 1 average, 2 count, 4 max, 5 min, 9 sum.", "SUBTOTAL(9, A1:A10)"),
  e("BASE", "Math", [req("number"), req("base"), opt("min_length")], "Converts a number to text in another base.", "BASE(255, 16)"),
  e("DECIMAL", "Math", [req("text"), req("base")], "Converts text in a given base to a number.", "DECIMAL(\"FF\", 16)"),

  /* ── Text ──────────────────────────────────────────────────────────── */
  e("PROPER", "Text", [req("text")], "Capitalises the first letter of each word.", "PROPER(\"hello world\")"),
  e("REPT", "Text", [req("text"), req("times")], "Repeats text a given number of times.", "REPT(\"-\", 10)"),
  e("EXACT", "Text", [req("text1"), req("text2")], "Tests whether two strings are identical, including case.", "EXACT(A1, B1)"),
  e("CHAR", "Text", [req("number")], "Returns the character for a code number.", "CHAR(65)"),
  e("CODE", "Text", [req("text")], "Returns the code number of the first character.", "CODE(\"A\")"),
  e("UNICHAR", "Text", [req("number")], "Returns the character for a Unicode code point.", "UNICHAR(8364)"),
  e("UNICODE", "Text", [req("text")], "Returns the Unicode code point of the first character.", "UNICODE(\"€\")"),
  e("CLEAN", "Text", [req("text")], "Removes non-printing characters from text.", "CLEAN(A1)"),
  e("REPLACE", "Text", [req("text"), req("position"), req("length"), req("new_text")], "Replaces part of a text string by position.", "REPLACE(\"abcdef\", 2, 3, \"XY\")"),
  e("TEXTJOIN", "Text", [req("delimiter"), req("ignore_empty"), req("text1"), rep("text2")], "Joins text with a delimiter, optionally skipping empties.", "TEXTJOIN(\", \", TRUE, A1:A5)"),
  e("JOIN", "Text", [req("delimiter"), req("value1"), rep("value2")], "Joins values with a delimiter between each.", "JOIN(\"-\", A1:A3)"),
  e("CONCAT", "Text", [req("value1"), rep("value2")], "Joins values and ranges into one text string.", "CONCAT(A1:A3)"),
  e("SPLIT", "Text", [req("text"), req("delimiter"), opt("split_by_each"), opt("remove_empty")], "Splits text around a delimiter into pieces; INDEX picks one.", "INDEX(SPLIT(\"a,b,c\", \",\"), 1, 2)"),
  e("REGEXMATCH", "Text", [req("text"), req("pattern")], "Tests whether text matches a regular expression.", "REGEXMATCH(A1, \"^\\d+$\")"),
  e("REGEXEXTRACT", "Text", [req("text"), req("pattern")], "Extracts the first match (or capture group) of a regular expression.", "REGEXEXTRACT(A1, \"\\d+\")"),
  e("REGEXREPLACE", "Text", [req("text"), req("pattern"), req("replacement")], "Replaces every match of a regular expression.", "REGEXREPLACE(A1, \"\\s+\", \" \")"),
  e("TEXTBEFORE", "Text", [req("text"), req("delimiter"), opt("instance")], "Returns the text before a delimiter; a negative instance counts from the end.", "TEXTBEFORE(\"a.b.c\", \".\")"),
  e("TEXTAFTER", "Text", [req("text"), req("delimiter"), opt("instance")], "Returns the text after a delimiter; a negative instance counts from the end.", "TEXTAFTER(\"a.b.c\", \".\", -1)"),
  e("NUMBERVALUE", "Text", [req("text"), opt("decimal_separator"), opt("group_separator")], "Converts text to a number using the given separators.", "NUMBERVALUE(\"1.234,56\", \",\", \".\")"),
  e("FIXED", "Text", [req("number"), opt("decimals"), opt("no_commas")], "Formats a number as text with fixed decimals and thousands separators.", "FIXED(1234.567, 1)"),
  e("DOLLAR", "Text", [req("number"), opt("decimals")], "Formats a number as currency text.", "DOLLAR(1234.5)"),
  e("ENCODEURL", "Text", [req("text")], "Encodes text for use in a web address.", "ENCODEURL(\"a b\")"),
  e("HYPERLINK", "Text", [req("url"), opt("label")], "Shows the label (or the address) for a link.", "HYPERLINK(\"https://example.com\", \"Site\")"),
  e("ASC", "Text", [req("text")], "Returns the text unchanged; kept for formulas from other spreadsheets.", "ASC(A1)"),

  /* ── Date ──────────────────────────────────────────────────────────── */
  e("DATEVALUE", "Date", [req("date_text")], "Converts a date written as text to a date serial number.", "DATEVALUE(\"2026-09-04\")"),
  e("TIMEVALUE", "Date", [req("time_text")], "Converts a time written as text to a fraction of a day.", "TIMEVALUE(\"1:45 pm\")"),
  e("TIME", "Date", [req("hour"), req("minute"), req("second")], "Returns a time as a fraction of a day.", "TIME(13, 45, 0)"),
  e("HOUR", "Date", [req("time")], "Returns the hour of a time, 0 to 23.", "HOUR(A1)"),
  e("MINUTE", "Date", [req("time")], "Returns the minute of a time, 0 to 59.", "MINUTE(A1)"),
  e("SECOND", "Date", [req("time")], "Returns the second of a time, 0 to 59.", "SECOND(A1)"),
  e("EDATE", "Date", [req("start_date"), req("months")], "Returns the date a number of months before or after another.", "EDATE(A1, 3)"),
  e("EOMONTH", "Date", [req("start_date"), req("months")], "Returns the last day of the month a number of months away.", "EOMONTH(A1, 0)"),
  e("DAYS", "Date", [req("end_date"), req("start_date")], "Returns the number of days between two dates.", "DAYS(B1, A1)"),
  e("DAYS360", "Date", [req("start_date"), req("end_date"), opt("method")], "Returns the days between two dates on a 360-day year.", "DAYS360(A1, B1)"),
  e("DATEDIF", "Date", [req("start_date"), req("end_date"), req("unit")], "Returns the difference between two dates in years, months or days (Y, M, D, YM, MD, YD).", "DATEDIF(A1, B1, \"M\")"),
  e("NETWORKDAYS", "Date", [req("start_date"), req("end_date"), opt("holidays")], "Counts the working days between two dates, skipping weekends and holidays.", "NETWORKDAYS(A1, B1)"),
  e("WORKDAY", "Date", [req("start_date"), req("days"), opt("holidays")], "Returns the date a number of working days from a start.", "WORKDAY(A1, 10)"),
  e("WEEKNUM", "Date", [req("date"), opt("type")], "Returns the week of the year a date falls in.", "WEEKNUM(A1)"),
  e("ISOWEEKNUM", "Date", [req("date")], "Returns the ISO week number of a date.", "ISOWEEKNUM(A1)"),
  e("YEARFRAC", "Date", [req("start_date"), req("end_date"), opt("basis")], "Returns the fraction of a year between two dates.", "YEARFRAC(A1, B1)"),
  e("MONTHNAME", "Date", [req("date")], "Returns the name of a date's month.", "MONTHNAME(A1)"),
  e("DAYNAME", "Date", [req("date")], "Returns the name of a date's weekday.", "DAYNAME(A1)"),
  e("DATEPART", "Date", [req("datetime")], "Returns the date half of a date-time, dropping the time.", "DATEPART(NOW())"),
  e("TIMEPART", "Date", [req("datetime")], "Returns the time half of a date-time as a fraction of a day.", "TIMEPART(NOW())"),

  /* ── Statistical ───────────────────────────────────────────────────── */
  e("LARGE", "Statistical", [req("range"), req("n")], "Returns the n-th largest value in a range.", "LARGE(A1:A10, 2)"),
  e("SMALL", "Statistical", [req("range"), req("n")], "Returns the n-th smallest value in a range.", "SMALL(A1:A10, 2)"),
  e("RANK", "Statistical", [req("value"), req("range"), opt("is_ascending")], "Returns the rank of a value in a range; ties share the top rank.", "RANK(A1, A1:A10)"),
  e("RANK.EQ", "Statistical", [req("value"), req("range"), opt("is_ascending")], "Returns the rank of a value in a range; ties share the top rank.", "RANK.EQ(A1, A1:A10)"),
  e("RANK.AVG", "Statistical", [req("value"), req("range"), opt("is_ascending")], "Returns the rank of a value; ties take the average rank.", "RANK.AVG(A1, A1:A10)"),
  e("PERCENTILE", "Statistical", [req("range"), req("percentile")], "Returns the value at a percentile (0 to 1) of a range.", "PERCENTILE(A1:A10, 0.9)"),
  e("PERCENTILE.INC", "Statistical", [req("range"), req("percentile")], "Returns the value at a percentile, including the ends.", "PERCENTILE.INC(A1:A10, 0.9)"),
  e("PERCENTILE.EXC", "Statistical", [req("range"), req("percentile")], "Returns the value at a percentile, excluding the ends.", "PERCENTILE.EXC(A1:A10, 0.9)"),
  e("QUARTILE", "Statistical", [req("range"), req("quartile")], "Returns a quartile (0 to 4) of a range.", "QUARTILE(A1:A10, 3)"),
  e("QUARTILE.INC", "Statistical", [req("range"), req("quartile")], "Returns a quartile of a range, including the ends.", "QUARTILE.INC(A1:A10, 1)"),
  e("QUARTILE.EXC", "Statistical", [req("range"), req("quartile")], "Returns a quartile of a range, excluding the ends.", "QUARTILE.EXC(A1:A10, 1)"),
  e("PERCENTRANK", "Statistical", [req("range"), req("value"), opt("significance")], "Returns where a value sits in a range as a fraction from 0 to 1.", "PERCENTRANK(A1:A10, 35)"),
  e("PERCENTRANK.INC", "Statistical", [req("range"), req("value"), opt("significance")], "Returns where a value sits in a range as a fraction from 0 to 1.", "PERCENTRANK.INC(A1:A10, 35)"),
  e("AVERAGEA", "Statistical", [req("value1"), rep("value2")], "Averages values, counting text as 0 and TRUE as 1.", "AVERAGEA(A1:A10)"),
  e("MAXA", "Statistical", [req("value1"), rep("value2")], "Returns the largest value, counting text as 0 and TRUE as 1.", "MAXA(A1:A10)"),
  e("MINA", "Statistical", [req("value1"), rep("value2")], "Returns the smallest value, counting text as 0 and TRUE as 1.", "MINA(A1:A10)"),
  e("COUNTBLANK", "Statistical", [req("range"), rep("range2")], "Counts the empty cells in a range.", "COUNTBLANK(A1:A10)"),
  e("COUNTUNIQUE", "Statistical", [req("value1"), rep("value2")], "Counts the distinct values in a range.", "COUNTUNIQUE(A1:A10)"),
  e("MAXIFS", "Statistical", [req("range"), req("criteria_range1"), req("criterion1"), rep("criteria_range2")], "Returns the largest value that meets every criterion.", "MAXIFS(B1:B10, A1:A10, \"east\")", "MAXIFS(range, criteria_range1, criterion1, [criteria_range2, criterion2, …])"),
  e("MINIFS", "Statistical", [req("range"), req("criteria_range1"), req("criterion1"), rep("criteria_range2")], "Returns the smallest value that meets every criterion.", "MINIFS(B1:B10, A1:A10, \"west\")", "MINIFS(range, criteria_range1, criterion1, [criteria_range2, criterion2, …])"),
  e("STDEV.S", "Statistical", [req("value1"), rep("value2")], "Returns the standard deviation of a sample.", "STDEV.S(A1:A10)"),
  e("STDEV.P", "Statistical", [req("value1"), rep("value2")], "Returns the standard deviation of a whole population.", "STDEV.P(A1:A10)"),
  e("STDEVP", "Statistical", [req("value1"), rep("value2")], "Returns the standard deviation of a whole population.", "STDEVP(A1:A10)"),
  e("VAR.S", "Statistical", [req("value1"), rep("value2")], "Returns the variance of a sample.", "VAR.S(A1:A10)"),
  e("VAR.P", "Statistical", [req("value1"), rep("value2")], "Returns the variance of a whole population.", "VAR.P(A1:A10)"),
  e("VARP", "Statistical", [req("value1"), rep("value2")], "Returns the variance of a whole population.", "VARP(A1:A10)"),
  e("GEOMEAN", "Statistical", [req("value1"), rep("value2")], "Returns the geometric mean of positive numbers.", "GEOMEAN(A1:A10)"),
  e("HARMEAN", "Statistical", [req("value1"), rep("value2")], "Returns the harmonic mean of positive numbers.", "HARMEAN(A1:A10)"),
  e("DEVSQ", "Statistical", [req("value1"), rep("value2")], "Returns the sum of squared deviations from the mean.", "DEVSQ(A1:A10)"),
  e("AVEDEV", "Statistical", [req("value1"), rep("value2")], "Returns the average absolute deviation from the mean.", "AVEDEV(A1:A10)"),
  e("CORREL", "Statistical", [req("range1"), req("range2")], "Returns the correlation coefficient of two ranges.", "CORREL(A1:A10, B1:B10)"),
  e("PEARSON", "Statistical", [req("range1"), req("range2")], "Returns the Pearson correlation coefficient of two ranges.", "PEARSON(A1:A10, B1:B10)"),
  e("COVAR", "Statistical", [req("range1"), req("range2")], "Returns the population covariance of two ranges.", "COVAR(A1:A10, B1:B10)"),
  e("COVARIANCE.P", "Statistical", [req("range1"), req("range2")], "Returns the population covariance of two ranges.", "COVARIANCE.P(A1:A10, B1:B10)"),
  e("COVARIANCE.S", "Statistical", [req("range1"), req("range2")], "Returns the sample covariance of two ranges.", "COVARIANCE.S(A1:A10, B1:B10)"),
  e("SLOPE", "Statistical", [req("known_y"), req("known_x")], "Returns the slope of the least-squares line through the points.", "SLOPE(B1:B10, A1:A10)"),
  e("INTERCEPT", "Statistical", [req("known_y"), req("known_x")], "Returns where the least-squares line crosses the y-axis.", "INTERCEPT(B1:B10, A1:A10)"),
  e("RSQ", "Statistical", [req("known_y"), req("known_x")], "Returns the square of the correlation coefficient.", "RSQ(B1:B10, A1:A10)"),
  e("FORECAST", "Statistical", [req("x"), req("known_y"), req("known_x")], "Predicts a y value at x along the least-squares line.", "FORECAST(12, B1:B10, A1:A10)"),
  e("FORECAST.LINEAR", "Statistical", [req("x"), req("known_y"), req("known_x")], "Predicts a y value at x along the least-squares line.", "FORECAST.LINEAR(12, B1:B10, A1:A10)"),
  e("NORM.DIST", "Statistical", [req("x"), req("mean"), req("standard_deviation"), req("cumulative")], "Returns the normal distribution at x, as a density or a cumulative probability.", "NORM.DIST(110, 100, 15, TRUE)"),
  e("NORMDIST", "Statistical", [req("x"), req("mean"), req("standard_deviation"), req("cumulative")], "Returns the normal distribution at x, as a density or a cumulative probability.", "NORMDIST(110, 100, 15, TRUE)"),
  e("NORM.S.DIST", "Statistical", [req("z"), opt("cumulative")], "Returns the standard normal distribution at z.", "NORM.S.DIST(1.96, TRUE)"),
  e("NORMSDIST", "Statistical", [req("z")], "Returns the cumulative standard normal distribution at z.", "NORMSDIST(1.96)"),
  e("NORM.INV", "Statistical", [req("probability"), req("mean"), req("standard_deviation")], "Returns the value whose cumulative normal probability is given.", "NORM.INV(0.975, 100, 15)"),
  e("NORMINV", "Statistical", [req("probability"), req("mean"), req("standard_deviation")], "Returns the value whose cumulative normal probability is given.", "NORMINV(0.975, 100, 15)"),
  e("NORM.S.INV", "Statistical", [req("probability")], "Returns the z whose cumulative standard normal probability is given.", "NORM.S.INV(0.975)"),
  e("NORMSINV", "Statistical", [req("probability")], "Returns the z whose cumulative standard normal probability is given.", "NORMSINV(0.975)"),
  e("STANDARDIZE", "Statistical", [req("x"), req("mean"), req("standard_deviation")], "Returns the z-score of a value.", "STANDARDIZE(110, 100, 15)"),
  e("CONFIDENCE.NORM", "Statistical", [req("alpha"), req("standard_deviation"), req("size")], "Returns the half-width of a confidence interval for a mean.", "CONFIDENCE.NORM(0.05, 2.5, 50)"),
  e("CONFIDENCE", "Statistical", [req("alpha"), req("standard_deviation"), req("size")], "Returns the half-width of a confidence interval for a mean.", "CONFIDENCE(0.05, 2.5, 50)"),
  e("SKEW", "Statistical", [req("value1"), rep("value2")], "Returns the skewness of a distribution.", "SKEW(A1:A10)"),
  e("KURT", "Statistical", [req("value1"), rep("value2")], "Returns the kurtosis of a distribution.", "KURT(A1:A10)"),
  e("TRIMMEAN", "Statistical", [req("range"), req("fraction")], "Returns the mean after dropping a fraction of the highest and lowest values.", "TRIMMEAN(A1:A10, 0.2)"),
  e("BINOM.DIST", "Statistical", [req("successes"), req("trials"), req("probability"), req("cumulative")], "Returns the binomial distribution probability.", "BINOM.DIST(6, 10, 0.5, FALSE)"),
  e("BINOMDIST", "Statistical", [req("successes"), req("trials"), req("probability"), req("cumulative")], "Returns the binomial distribution probability.", "BINOMDIST(6, 10, 0.5, FALSE)"),
  e("POISSON.DIST", "Statistical", [req("x"), req("mean"), req("cumulative")], "Returns the Poisson distribution probability.", "POISSON.DIST(2, 3, FALSE)"),
  e("POISSON", "Statistical", [req("x"), req("mean"), req("cumulative")], "Returns the Poisson distribution probability.", "POISSON(2, 3, FALSE)"),

  /* ── Lookup ────────────────────────────────────────────────────────── */
  e("ROW", "Lookup", [opt("reference")], "Returns the row number of a reference, or of the formula's own cell.", "ROW(B7)"),
  e("COLUMN", "Lookup", [opt("reference")], "Returns the column number of a reference, or of the formula's own cell.", "COLUMN(B7)"),
  e("ROWS", "Lookup", [req("range")], "Returns the number of rows in a range.", "ROWS(A1:A10)"),
  e("COLUMNS", "Lookup", [req("range")], "Returns the number of columns in a range.", "COLUMNS(A1:D1)"),
  e("CHOOSE", "Lookup", [req("index"), req("value1"), rep("value2")], "Returns the value at a position in the list.", "CHOOSE(2, \"a\", \"b\", \"c\")"),
  e("LOOKUP", "Lookup", [req("value"), req("lookup_range"), opt("result_range")], "Finds the largest entry at or below a value in a sorted range and returns the matching result.", "LOOKUP(7, A1:A10, B1:B10)"),
  e("XMATCH", "Lookup", [req("value"), req("range"), opt("match_mode"), opt("search_mode")], "Returns the position of a value; match mode 0 exact, -1 next smaller, 1 next larger, 2 wildcard.", "XMATCH(20, A1:A10)"),
  e("ADDRESS", "Lookup", [req("row"), req("column"), opt("absolute"), opt("a1"), opt("sheet")], "Builds a cell address as text.", "ADDRESS(2, 3)"),

  /* ── Array ─────────────────────────────────────────────────────────── */
  e("TRANSPOSE", "Array", [req("range")], "Swaps the rows and columns of a range.", "SUM(TRANSPOSE(A1:C1))"),
  e("SEQUENCE", "Array", [req("rows"), opt("columns"), opt("start"), opt("step")], "Returns a grid of numbers counting from a start by a step.", "SUM(SEQUENCE(10))"),
  e("SORTBY", "Array", [req("range"), req("by_range"), opt("order")], "Sorts the rows of a range by the values of another.", "INDEX(SORTBY(A1:A10, B1:B10), 1, 1)"),
  e("FLATTEN", "Array", [req("range1"), rep("range2")], "Puts every value of the ranges into one column.", "COUNTUNIQUE(FLATTEN(A1:C10))"),

  /* ── Financial ─────────────────────────────────────────────────────── */
  e("PMT", "Financial", [req("rate"), req("periods"), req("present_value"), opt("future_value"), opt("type")], "Returns the payment per period for a loan or annuity.", "PMT(5%/12, 60, 20000)"),
  e("FV", "Financial", [req("rate"), req("periods"), req("payment"), opt("present_value"), opt("type")], "Returns the future value of regular payments at a fixed rate.", "FV(5%/12, 60, -300)"),
  e("PV", "Financial", [req("rate"), req("periods"), req("payment"), opt("future_value"), opt("type")], "Returns the present value of regular payments at a fixed rate.", "PV(5%/12, 60, -377.42)"),
  e("NPER", "Financial", [req("rate"), req("payment"), req("present_value"), opt("future_value"), opt("type")], "Returns the number of periods needed to pay off a value.", "NPER(5%/12, -377.42, 20000)"),
  e("RATE", "Financial", [req("periods"), req("payment"), req("present_value"), opt("future_value"), opt("type"), opt("guess")], "Returns the per-period interest rate of a loan or annuity.", "RATE(60, -377.42, 20000)"),
  e("IPMT", "Financial", [req("rate"), req("period"), req("periods"), req("present_value"), opt("future_value"), opt("type")], "Returns the interest part of a given period's payment.", "IPMT(5%/12, 1, 60, 20000)"),
  e("PPMT", "Financial", [req("rate"), req("period"), req("periods"), req("present_value"), opt("future_value"), opt("type")], "Returns the principal part of a given period's payment.", "PPMT(5%/12, 1, 60, 20000)"),
  e("CUMIPMT", "Financial", [req("rate"), req("periods"), req("present_value"), req("first_period"), req("last_period"), req("type")], "Returns the interest paid between two periods.", "CUMIPMT(5%/12, 60, 20000, 1, 12, 0)"),
  e("CUMPRINC", "Financial", [req("rate"), req("periods"), req("present_value"), req("first_period"), req("last_period"), req("type")], "Returns the principal paid between two periods.", "CUMPRINC(5%/12, 60, 20000, 1, 12, 0)"),
  e("NPV", "Financial", [req("rate"), req("value1"), rep("value2")], "Returns the net present value of cash flows at a discount rate.", "NPV(10%, A2:A5) + A1"),
  e("IRR", "Financial", [req("cash_flows"), opt("guess")], "Returns the internal rate of return of a series of cash flows.", "IRR(A1:A5)"),
  e("MIRR", "Financial", [req("cash_flows"), req("finance_rate"), req("reinvest_rate")], "Returns the modified internal rate of return.", "MIRR(A1:A5, 10%, 12%)"),
  e("XNPV", "Financial", [req("rate"), req("cash_flows"), req("dates")], "Returns the net present value of cash flows on given dates.", "XNPV(10%, A1:A5, B1:B5)"),
  e("XIRR", "Financial", [req("cash_flows"), req("dates"), opt("guess")], "Returns the internal rate of return of cash flows on given dates.", "XIRR(A1:A5, B1:B5)"),
  e("SLN", "Financial", [req("cost"), req("salvage"), req("life")], "Returns straight-line depreciation for one period.", "SLN(10000, 1000, 5)"),
  e("SYD", "Financial", [req("cost"), req("salvage"), req("life"), req("period")], "Returns sum-of-years-digits depreciation for a period.", "SYD(10000, 1000, 5, 1)"),
  e("DDB", "Financial", [req("cost"), req("salvage"), req("life"), req("period"), opt("factor")], "Returns double-declining-balance depreciation for a period.", "DDB(10000, 1000, 5, 1)"),
  e("DB", "Financial", [req("cost"), req("salvage"), req("life"), req("period"), opt("month")], "Returns fixed-declining-balance depreciation for a period.", "DB(10000, 1000, 5, 1)"),
  e("EFFECT", "Financial", [req("nominal_rate"), req("periods_per_year")], "Returns the effective annual rate from a nominal rate.", "EFFECT(5%, 12)"),
  e("NOMINAL", "Financial", [req("effective_rate"), req("periods_per_year")], "Returns the nominal annual rate from an effective rate.", "NOMINAL(5.12%, 12)"),
  e("RRI", "Financial", [req("periods"), req("present_value"), req("future_value")], "Returns the rate that grows one value into another over the periods.", "RRI(10, 1000, 2000)"),
  e("PDURATION", "Financial", [req("rate"), req("present_value"), req("future_value")], "Returns the periods needed for a value to grow to another at a rate.", "PDURATION(7%, 1000, 2000)"),
  e("DOLLARDE", "Financial", [req("fractional_price"), req("fraction")], "Converts a price quoted as a fraction to a decimal.", "DOLLARDE(1.02, 16)"),
  e("DOLLARFR", "Financial", [req("decimal_price"), req("fraction")], "Converts a decimal price to one quoted as a fraction.", "DOLLARFR(1.125, 16)"),

  /* ── Info ──────────────────────────────────────────────────────────── */
  e("ISNUMBER", "Info", [req("value")], "Tests whether a value is a number.", "ISNUMBER(A1)"),
  e("ISTEXT", "Info", [req("value")], "Tests whether a value is text.", "ISTEXT(A1)"),
  e("ISNONTEXT", "Info", [req("value")], "Tests whether a value is anything but text.", "ISNONTEXT(A1)"),
  e("ISLOGICAL", "Info", [req("value")], "Tests whether a value is TRUE or FALSE.", "ISLOGICAL(A1)"),
  e("ISBLANK", "Info", [req("value")], "Tests whether a cell is empty.", "ISBLANK(A1)"),
  e("ISERROR", "Info", [req("value")], "Tests whether a value is any error.", "ISERROR(A1/B1)"),
  e("ISERR", "Info", [req("value")], "Tests whether a value is an error other than #N/A.", "ISERR(A1)"),
  e("ISNA", "Info", [req("value")], "Tests whether a value is the #N/A error.", "ISNA(VLOOKUP(A1, B:C, 2, FALSE))"),
  e("ISEVEN", "Info", [req("value")], "Tests whether a number is even.", "ISEVEN(A1)"),
  e("ISODD", "Info", [req("value")], "Tests whether a number is odd.", "ISODD(A1)"),
  e("N", "Info", [req("value")], "Returns a value as a number: TRUE is 1, text is 0.", "N(TRUE)"),
  e("T", "Info", [req("value")], "Returns a value if it is text, otherwise empty text.", "T(A1)"),
  e("NA", "Info", [], "Returns the #N/A error.", "NA()"),
  e("TYPE", "Info", [req("value")], "Returns a number for the value's type: 1 number, 2 text, 4 logical, 16 error, 64 array.", "TYPE(A1)"),
  e("ERROR.TYPE", "Info", [req("value")], "Returns a number for the kind of error a value holds.", "ERROR.TYPE(A1)"),

  /* ── Visual ────────────────────────────────────────────────────────── */
  e("SPARKLINE", "Visual", [req("data"), opt("type"), opt("colour"), opt("min"), opt("max")], "Draws a tiny chart of the numbers in the cell: line, bar, column or winloss.", 'SPARKLINE(B2:B13, "column")'),
  e("IMAGE", "Visual", [req("url"), opt("mode")], "Shows a picture from an https address in the cell; mode 1 fits, 2 stretches, 3 keeps its size.", 'IMAGE("https://example.com/logo.png")'),

  /* ── Engineering ───────────────────────────────────────────────────── */
  e("BIN2DEC", "Engineering", [req("binary")], "Converts a binary number to decimal.", "BIN2DEC(1010)"),
  e("BIN2HEX", "Engineering", [req("binary"), opt("places")], "Converts a binary number to hexadecimal.", "BIN2HEX(1010)"),
  e("BIN2OCT", "Engineering", [req("binary"), opt("places")], "Converts a binary number to octal.", "BIN2OCT(1010)"),
  e("DEC2BIN", "Engineering", [req("number"), opt("places")], "Converts a decimal number to binary.", "DEC2BIN(10, 8)"),
  e("DEC2HEX", "Engineering", [req("number"), opt("places")], "Converts a decimal number to hexadecimal.", "DEC2HEX(255)"),
  e("DEC2OCT", "Engineering", [req("number"), opt("places")], "Converts a decimal number to octal.", "DEC2OCT(15)"),
  e("HEX2DEC", "Engineering", [req("hexadecimal")], "Converts a hexadecimal number to decimal.", "HEX2DEC(\"FF\")"),
  e("HEX2BIN", "Engineering", [req("hexadecimal"), opt("places")], "Converts a hexadecimal number to binary.", "HEX2BIN(\"A\")"),
  e("HEX2OCT", "Engineering", [req("hexadecimal"), opt("places")], "Converts a hexadecimal number to octal.", "HEX2OCT(\"FF\")"),
  e("OCT2DEC", "Engineering", [req("octal")], "Converts an octal number to decimal.", "OCT2DEC(17)"),
  e("OCT2BIN", "Engineering", [req("octal"), opt("places")], "Converts an octal number to binary.", "OCT2BIN(17)"),
  e("OCT2HEX", "Engineering", [req("octal"), opt("places")], "Converts an octal number to hexadecimal.", "OCT2HEX(17)"),
  e("BITAND", "Engineering", [req("value1"), req("value2")], "Returns the bitwise AND of two numbers.", "BITAND(12, 10)"),
  e("BITOR", "Engineering", [req("value1"), req("value2")], "Returns the bitwise OR of two numbers.", "BITOR(12, 10)"),
  e("BITXOR", "Engineering", [req("value1"), req("value2")], "Returns the bitwise exclusive OR of two numbers.", "BITXOR(12, 10)"),
  e("BITLSHIFT", "Engineering", [req("value"), req("shift")], "Shifts the bits of a number to the left.", "BITLSHIFT(1, 4)"),
  e("BITRSHIFT", "Engineering", [req("value"), req("shift")], "Shifts the bits of a number to the right.", "BITRSHIFT(16, 2)"),
  e("DELTA", "Engineering", [req("number1"), opt("number2")], "Returns 1 when two numbers are equal, otherwise 0.", "DELTA(2, 2)"),
  e("GESTEP", "Engineering", [req("number"), opt("step")], "Returns 1 when a number is at least the step, otherwise 0.", "GESTEP(5, 3)"),
  e("CONVERT", "Engineering", [req("value"), req("from_unit"), req("to_unit")], "Converts a value between units of length, mass, time, volume, area, speed, temperature and more.", "CONVERT(1, \"mi\", \"km\")"),
];

export const MORE_FUNCTION_HELP: Record<string, FunctionHelp> = Object.fromEntries(entries.map((h) => [h.name, h]));
